#Offical python runtime
FROM python:3.8

#Copy the current directory contents into the containter at /app
ADD . /app
COPY requirements.txt /tmp/

#Install any needed packaged specifed in .\requirements.txt
RUN pip install --trusted-host pypip.python.org  -r /tmp/requirements.txt

#Ports

#Environemnt variable
ENV NATSaddress=nats://demo.nats.io:4222
ENV communicator=NATS


#Run app when the container launches

CMD python /app/main.py -c $communicator -ns $NATSaddress