#Offical python runtime
FROM python:3.8

#Copy the current directory contents into the containter at /app
ADD . /app
COPY requirements.txt /tmp/

#Install any needed packaged specifed in .\requirements.txt
RUN pip install --trusted-host pypip.python.org  -r /tmp/requirements.txt

#Opencv hotfix
RUN apt-get update -y
RUN apt install libgl1-mesa-glx -y
RUN apt-get install 'ffmpeg'\
    'libsm6'\
    'libxext6'  -y

#Environemnt variable
ENV EastCoordinate=44.0
ENV NorthCoordiante=44.0
ENV FramesPerSecond=1
ENV NATSaddress=nats://demo.nats.io:4222
ENV CSVFile=/app/dataset.csv
ENV Port=9000
ENV Name=Sensor1
ENV ServiceRegistry=http://127.0.0.1:8761/
ENV SkipNFrames=0

#Run app when the container launches

CMD python /app/main.py -p $Port -n $Name -ns $NATSaddress -csv $CSVFile -N $NorthCoordiante -E $EastCoordinate -fps $FramesPerSecond -r $ServiceRegistry -s $SkipNFrames