#Offical python runtime
FROM python:3.8

#Copy the current directory contents into the containter at /app
ADD . /app
COPY requirements.txt /tmp/

#Install any needed packaged specifed in .\requirements.txt
RUN pip install --trusted-host pypip.python.org  -r /tmp/requirements.txt

#Opencv hotfix
RUN apt-get update -y
RUN apt install libgl1-mesa-glx -y
RUN apt-get install 'ffmpeg'\
    'libsm6'\
    'libxext6'  -y

#Environemnt variable
ENV NATSaddress=nats://demo.nats.io:4222
ENV communicator=NATS
ENV DataBaseAddress=mongodb://localhost:27017
ENV DataBaseType=Mongo
ENV InternalPort=9010
ENV Name=Data1
ENV ServiceRegistry=http://127.0.0.1:8761/


#Run app when the container launches

CMD python /app/main.py -c $communicator -ns $NATSaddress -p $InternalPort -n $Name -db $DataBaseType  -DBa $DataBaseAddress -r $ServiceRegistry